import {
  Plane,
  Hotel,
  MapPin,
  Utensils,
  ShoppingBag,
  Train,
  Info,
} from "lucide-react";

export const tripData = {
  flight: [
    {
      date: "03/01",
      route: "TPE -> NRT",
      time: "15:40 - 19:55",
      flightNo: "Peach MM 628",
      type: "flight",
      baggage: "手提行李：合計兩件總共7kg\n托運行李：共一件20kg"
    },
    {
      date: "03/05",
      route: "HND -> HKD",
      time: "09:40 - 11:00",
      flightNo: "ANA NH 553",
      type: "flight",
      baggage: "手提行李：合計兩件總共10kg\n托運行李：不限件數，總重20kg"
    },
    {
      date: "03/10",
      route: "CTS -> TPE",
      time: "11:55 - 15:35",
      flightNo: "Tigerair IT 235",
      type: "flight",
      baggage: "手提行李：合計兩件總共10kg\n托運行李：不限件數，總重20kg"
    },
  ],
  shopping: {
    sapporo: [
      {
        name: "HOKA Fukuoka Tenjin",
        building: "Standalone",
        floor: "1F",
        hours: "11:00 - 20:00",
        link: "https://maps.app.goo.gl/AhT9FQU2SYxCUhDA8",
      },
      {
        name: "Super Sports Xebio Fukuoka Tenjin",
        building: "Standalone",
        floor: "1F",
        hours: "10:00 - 21:00",
        link: "https://maps.app.goo.gl/eDGBA2UK6RQuneh87",
      },
      {
        name: "Mina Tenjin",
        isBuilding: true,
        hours: "10:00 - 20:00",
        shops: [
          {
            name: "3COINS＋",
            floor: "B1F",
            link: "https://maps.app.goo.gl/CU5TtzJ3RE9v4tnY7",
          },
          {
            name: "UNIQLO",
            floor: "1F-2F",
            link: "https://maps.app.goo.gl/oiVDfiSjVvLoyRmk8",
          },
          {
            name: "GU",
            floor: "3F",
            link: "https://maps.app.goo.gl/o4hrRNPQzuM9d6Ni8",
          },
          {
            name: "LOFT",
            floor: "4F",
            link: "https://maps.app.goo.gl/67iMaH4ygF64y7xX8",
          },
        ],
      },
      {
        name: "天神地下街",
        building: "Underground",
        hours: "10:00 - 20:00",
        link: "https://maps.app.goo.gl/6wAuWeLaQ7m6FnHN8",
      },
      {
        name: "PARCO Fukuoka",
        isBuilding: true,
        hours: "10:00 - 20:30",
        shops: [
          {
            name: "Onitsuka Tiger",
            floor: "Main Bldg 3F",
            link: "https://maps.app.goo.gl/PKJcnZVR1Fb1w2rQA",
          },
          {
            name: "9090",
            floor: "Main Bldg 3F",
            link: "https://maps.app.goo.gl/ydb4n1qR4r4DadsHA",
          },
          {
            name: "Lui’s",
            floor: "Main Bldg 3F",
            link: "https://maps.app.goo.gl/5NbbUX4bjui2iu9u9",
          },
          {
            name: "ABC-MART Grand Stage",
            floor: "Main Bldg 3F",
            link: "https://maps.app.goo.gl/JfzZ8zZUNoo3xBRGA",
          },
          {
            name: "SNIDEL",
            floor: "Main Bldg 4F",
            link: "https://maps.app.goo.gl/cPGyvz7BgK8tWZ52A",
          },
          {
            name: "Francfranc",
            floor: "Main Bldg 5F",
            link: "https://maps.app.goo.gl/C3fXMNXPqefDycyL6",
          },
          {
            name: "BEAMS",
            floor: "New Bldg 1F-2F",
            link: "https://maps.app.goo.gl/AJSXxSANUdLgE1ah8",
          },
          {
            name: "HARE",
            floor: "New Bldg 3F",
            link: "https://maps.app.goo.gl/3vrmV18mAawmVqw1A",
          },
          {
            name: "FREAK’S STORE",
            floor: "New Bldg 4F",
            link: "https://maps.app.goo.gl/7tgNznxC4pkZjikk9",
          },
        ],
      },
      {
        name: "ABC-MART Grand Stage Tenjin",
        building: "Standalone",
        floor: "1F-3F",
        hours: "11:00 - 21:00",
        link: "https://maps.app.goo.gl/tp7eAykqyWW9T78BA",
      },
      {
        name: "Adidas Originals Shop",
        building: "Standalone",
        floor: "1F",
        hours: "11:00 - 20:00",
        link: "https://maps.app.goo.gl/pmogb8QkuJvjLonv8",
      },
      {
        name: "Factory",
        building: "Standalone",
        floor: "1F",
        hours: "13:00 - 18:00",
        link: "https://maps.app.goo.gl/RvSJVkHfFkSYMyMf8",
      },
      {
        name: "Dice & Dice",
        building: "Standalone",
        floor: "1F",
        hours: "13:00 - 18:00",
        link: "https://maps.app.goo.gl/Ua9n4WMQmYXZCYay8",
      },
      {
        name: "ZARA Tenjin Nishi-dori",
        building: "Standalone",
        floor: "1F-3F",
        hours: "11:00 - 21:00",
        link: "https://maps.app.goo.gl/Xrxwm1MxqdareXKo8",
      },
      {
        name: "大賀藥局 (Oga Pharmacy)",
        building: "Standalone",
        floor: "1F",
        hours: "10:00 - 22:00",
        link: "https://maps.app.goo.gl/VeBCd8cwSFmkfXfE8",
      },
    ],
    hakodate: [
      {
        name: "AMU PLAZA Hakata",
        isBuilding: true,
        hours: "10:00 - 20:00",
        shops: [
          {
            name: "Le Dome (Édifice/Iéna)",
            floor: "3F",
            link: "https://maps.app.goo.gl/jzqbSAUmET3wF4NQ9",
          },
          {
            name: "BEAMS",
            floor: "3F",
            link: "https://maps.app.goo.gl/iCcZZhPZq8ejruLW6",
          },
          {
            name: "FREAK’S STORE",
            floor: "4F",
            link: "https://maps.app.goo.gl/b1izKYHJ4yMRgwDe9",
          },
          {
            name: "atmos",
            floor: "5F",
            link: "https://maps.app.goo.gl/n4Vs7cBi3YLRdhxQ6",
          },
          {
            name: "MUJI",
            floor: "6F",
            link: "https://maps.app.goo.gl/Gakfdg8VufxCiBU26",
          },
          {
            name: "ABC-MART",
            floor: "7F",
            link: "https://maps.app.goo.gl/2coZLK3pjuuhAiqB7",
          },
        ],
      },
      {
        name: "AMU EST",
        isBuilding: true,
        hours: "10:00 - 20:00",
        shops: [
          {
            name: "LOWRYS FARM",
            floor: "B1F",
            link: "https://maps.app.goo.gl/jeEdzq12MYoiFoeW7",
          },
          {
            name: "UNIQLO",
            floor: "1F",
            link: "https://maps.app.goo.gl/3BvK8xANZNywev6a7",
          },
        ],
      },
      {
        name: "KITTE Hakata",
        isBuilding: true,
        hours: "10:00 - 21:00",
        shops: [
          {
            name: "UNIQLO",
            floor: "8F",
            hours: "10:00 - 21:00",
            link: "https://maps.app.goo.gl/vpc2qq8bh7DoTbUN8",
          },
        ],
      },
      {
        name: "CANAL CITY Hakata",
        isBuilding: true,
        hours: "10:00 - 21:00",
        shops: [
          {
            name: "RAGEBLUE",
            floor: "North Bldg 2F",
            link: "https://maps.app.goo.gl/xFkdyyTTst84dLzy8",
          },
          {
            name: "MUJI",
            floor: "North Bldg 3F-4F",
            link: "https://maps.app.goo.gl/VLNEuqq8FgtDWhLW9",
          },
          {
            name: "Adidas Originals",
            floor: "Center Walk 1F",
            link: "https://maps.app.goo.gl/3odaPqBG6DA15sf39",
          },
          {
            name: "MOUSSY",
            floor: "Center Walk 2F",
            link: "https://maps.app.goo.gl/QxHoaxJfeXue31ng9",
          },
          {
            name: "Asics",
            floor: "Center Walk 2F",
            link: "https://maps.app.goo.gl/7UzytRJtTVGMkVbc8",
          },
          {
            name: "Levi’s",
            floor: "Center Walk 2F",
            link: "https://maps.app.goo.gl/Xiz2YmqPAR5d7fLy5",
          },
          {
            name: "ABC-MART Grand Stage",
            floor: "Center Walk 3F",
            link: "https://maps.app.goo.gl/R48HbE8Jj1mmJNZb9",
          },
          {
            name: "Alpen Fukuoka",
            floor: "South Bldg 1F-3F",
            link: "https://maps.app.goo.gl/ThnejdLYkkYmfB5H7",
          },
          {
            name: "Onitsuka Tiger",
            floor: "South Bldg 2F",
            link: "https://maps.app.goo.gl/3MKG63X1FCaWU94D9",
          },
        ],
      },
    ],
  },
  food: {
    sapporo: [
      {
        category: "咖啡廳",
        shops: [
          {
            name: "The Full Full",
            link: "https://maps.app.goo.gl/LHHurbd9sAQtgUo6A",
            hours: "10:00 - 20:00",
            desc: "著名的明太子法國麵包與烘焙咖啡。",
          },
          {
            name: "藍瓶咖啡 Blue Bottle Coffee",
            link: "https://maps.app.goo.gl/vfv5WZg1MmPDLGG78",
            hours: "08:00 - 20:00",
            desc: "精品咖啡，店內氛圍靜謐。",
          },
        ],
      },
      {
        category: "甜點",
        shops: [
          {
            name: "ASAKO IWAYANAGI FUKUOKA",
            link: "https://maps.app.goo.gl/cMMPu1wgPTrVmxwr9",
            hours: "11:00 - 20:00",
            desc: "精緻華麗的芭菲與甜點藝術。",
          },
        ],
      },
      {
        category: "丼飯",
        shops: [
          {
            name: "黒田飯",
            link: "https://maps.app.goo.gl/rXPeRvUyoAzfPSLW9",
            hours: "11:30 - 14:00 / 18:00 - 22:00",
            desc: "在地特色丼飯與日式料理。",
          },
        ],
      },
    ],
    nakasu: [
      {
        category: "拉麵",
        shops: [
          {
            name: "一蘭 本社総本店",
            link: "https://maps.app.goo.gl/bwLkRDyBGLX4QGtA6",
            hours: "24 小時營業",
            desc: "一蘭拉麵全球總本店，感受最道地的氛圍。",
          },
        ],
      },
      {
        category: "屋台",
        shops: [
          {
            name: "中洲屋台街",
            link: "https://maps.app.goo.gl/W1oZfQnYa5MgMoxV7",
            hours: "18:00 - 24:00",
            desc: "福岡最具代表性的夜間路邊攤文化。",
          },
        ],
      },
    ],
    hakodate: [
      {
        category: "拉麵",
        shops: [
          {
            name: "博多一双",
            link: "https://maps.app.goo.gl/Y5Lria8iFp5oQdnU8",
            hours: "11:00 - 24:00",
            desc: "濃厚系的豚骨拉麵，排隊人氣名店。",
          },
          {
            name: "麺屋 いしヰ",
            link: "https://maps.app.goo.gl/Rb9mkZ127C1f5MyZ8",
            hours: "11:00 - 15:00 / 17:00 - 21:00",
            desc: "特色沾麵與精緻拉麵料理。",
          },
        ],
      },
      {
        category: "燒肉",
        shops: [
          {
            name: "博多 焼肉 八十八―YASOHACHI",
            link: "https://maps.app.goo.gl/rd1Kdn5bSxVEvvMu9",
            hours: "11:30 - 14:30 / 17:00 - 23:00",
            desc: "高品質和牛燒肉，環境優雅。",
          },
        ],
      },
      {
        category: "火鍋",
        shops: [
          {
            name: "博多牛腸鍋 前田屋",
            link: "https://maps.app.goo.gl/p6ZDh8ugnxabm7P69",
            hours: "11:00 - 15:00 / 17:00 - 23:00",
            desc: "福岡名物牛腸鍋，湯頭鮮美。",
          },
        ],
      },
      {
        category: "咖啡廳",
        shops: [
          {
            name: "Dacomecca",
            link: "https://maps.app.goo.gl/VvoVz7BfkViapyZn9",
            hours: "08:00 - 19:00",
            desc: "美術館般的麵包名店，視覺與味覺雙重享受。",
          },
          {
            name: "The Full Full Hakata",
            link: "https://maps.app.goo.gl/2dZFZWGBq3cLNTUy7",
            hours: "08:00 - 21:00",
            desc: "明太子法國麵包代表店，近博多站。",
          },
          {
            name: "FUK COFFEE",
            link: "https://maps.app.goo.gl/mFtDAdeWpFM2owAz9",
            hours: "08:00 - 20:00",
            desc: "以旅遊為主題的特色咖啡店。",
          },
        ],
      },
      {
        category: "甜點",
        shops: [
          {
            name: "蜂樂饅頭",
            link: "https://maps.app.goo.gl/k8gvtBbfNDp3h5Zd9",
            hours: "10:00 - 19:00",
            desc: "經典日式甜點，內餡飽滿紮實。",
          },
        ],
      },
      {
        category: "居酒屋",
        shops: [
          {
            name: "博多かわ屋",
            link: "https://maps.app.goo.gl/J1hb3Jk5zJUAJRR9A",
            hours: "17:00 - 24:00",
            desc: "招牌烤雞皮串，福岡必吃美食。",
          },
        ],
      },
    ],
  },
  accommodation: [
    {
      region: "東京",
      name: "LANDABOUT TOKYO",
      address: "3-4-5 Negishi, Taito, Tokyo, 110-0003, 日本",
      checkIn: "03/01 15:00",
      checkOut: "03/05 11:00",
      mapUrl: "https://maps.app.goo.gl/ex4LRq41YRcABJ17A",
      type: "hotel",
      note: "禁菸客房、免費 WiFi、餐廳（Landabout Table）提供歐陸式早餐（07:00–10:00，約 JPY 1,650／人）。最近車站：鶯谷站步行約3分鐘",
    },
    {
      region: "函館",
      name: "OMO5 函館 by 星野集團",
      address: "〒040-0063 北海道函館市若松町24-1",
      checkIn: "03/05 15:00",
      checkOut: "03/06 11:00",
      mapUrl: "https://maps.app.goo.gl/CAbQZTZLamMNQpm99",
      type: "hotel",
      note: "溫泉（源泉掛流式）、OMO Base 公共空間（咖啡廳/酒吧/露台）、海鮮自助早餐、免費 WiFi。從 JR 函館車站步行約5分鐘。免費巡迴接駁巴士（函館免費周遊巴士）",
    },
    {
      region: "小樽",
      name: "小樽格里茲頂級飯店",
      address: "〒047-0032 北海道小樽市稲穂1丁目3-13",
      checkIn: "03/06 15:00",
      checkOut: "03/07 11:00",
      mapUrl: "https://maps.app.goo.gl/CbCAumFE6t2d5ya48",
      type: "hotel",
      note: "免費 WiFi、現代化設計。詳細資訊請參考官方網站",
    },
    {
      region: "富良野",
      name: "THE ARBANO",
      address: "北海道富良野市錦町富良野市西き町7-13",
      checkIn: "03/07 15:00",
      checkOut: "03/08 10:00",
      mapUrl: "https://maps.app.goo.gl/XdBVGQVBCHp6vLHD8",
      type: "airbnb",
      note: "Airbnb 住宿。詳細資訊請參考 Airbnb 頁面",
    },
    {
      region: "札幌",
      name: "札幌格蘭貝爾酒店",
      address: "北海道札幌市中央区南三条西8丁目10-1",
      checkIn: "03/08 15:00",
      checkOut: "03/09 11:00",
      mapUrl: "https://maps.app.goo.gl/WvqwfNPh7w1TcUGw8",
      type: "hotel",
      note: "天空露天風呂（屋頂露天浴池）、和洋自助早餐約60種、免費 WiFi。從地鐵「すすきの駅」步行約8分鐘",
    },
    {
      region: "新千歲",
      name: "機場航站飯店",
      address: "新千歲機場國內航站樓內",
      checkIn: "03/09 14:00",
      checkOut: "03/10 11:00",
      mapUrl: "https://maps.app.goo.gl/QL8d9AqpSWEfANd79",
      type: "hotel",
      note: "直接連接國內航站樓、免費 WiFi、機場溫泉（住客免費使用）、日式/西式自助早餐（6:00-9:30）。從 JR 新千歲機場站步行約5分鐘",
    },
  ],
  emergency: [
    { name: "Police", number: "110" },
    { name: "Fire/Ambulance", number: "119" },
    { name: "TECO Sapporo", number: "+81-11-644-1981" },
  ],
  itinerary: [
    {
      day: 1,
      date: "03/01 (週日)",
      title: "行程規劃中",
      location: "北海道",
      weather: "",
      image:
        "https://images.unsplash.com/photo-1623310073404-fe9953eadb04?auto=format&fit=crop&w=1200&q=80",
      activities: [],
    },
    {
      day: 2,
      date: "03/02 (週一)",
      title: "行程規劃中",
      location: "北海道",
      weather: "",
      image:
        "https://images.unsplash.com/photo-1623310073404-fe9953eadb04?auto=format&fit=crop&w=1200&q=80",
      activities: [],
    },
    {
      day: 3,
      date: "03/03 (週二)",
      title: "行程規劃中",
      location: "北海道",
      weather: "",
      image:
        "https://images.unsplash.com/photo-1623310073404-fe9953eadb04?auto=format&fit=crop&w=1200&q=80",
      activities: [],
    },
    {
      day: 4,
      date: "03/04 (週三)",
      title: "行程規劃中",
      location: "北海道",
      weather: "",
      image:
        "https://images.unsplash.com/photo-1623310073404-fe9953eadb04?auto=format&fit=crop&w=1200&q=80",
      activities: [],
    },
    {
      day: 5,
      date: "03/05 (週四)",
      title: "函館一日遊",
      location: "函館",
      weather: "",
      image:
        "https://images.unsplash.com/photo-1623310073404-fe9953eadb04?auto=format&fit=crop&w=1200&q=80",
      activities: [
        {
          time: "11:10",
          type: "交通",
          title: "函館機場(HKD)",
          desc: "抵達函館機場，辦理入境手續",
          about: "函館機場是北海道南部的主要機場，距離函館市區約20分鐘車程。",
          nav: "函館機場",
        },
        {
          time: "12:29",
          type: "住宿",
          title: "OMO5 函館 by 星野集團",
          desc: "抵達飯店，辦理入住手續",
          about: "OMO5 函館 by 星野集團位於函館市中心，距離 JR 函館車站步行約5分鐘。飯店提供溫泉、OMO Base 公共空間等設施。",
          nav: "OMO5 函館 by 星野集團",
        },
        {
          time: "12:57",
          type: "美食",
          title: "函館朝市 駅二市場",
          desc: "在函館朝市享用新鮮海鮮料理",
          about: "函館朝市是北海道最著名的海鮮市場之一，提供新鮮的海鮮丼、壽司等料理。駅二市場是朝市內的主要市場區域。",
          nav: "函館朝市 駅二市場",
        },
        {
          time: "14:10",
          type: "景點",
          title: "五稜郭公園",
          desc: "參觀星形要塞遺跡，欣賞歷史建築與櫻花",
          about: "五稜郭是日本第一座西式星形要塞，建於江戶時代末期。春天時櫻花盛開，是函館最著名的賞櫻景點之一。可以登上五稜郭塔俯瞰星形全景。",
          nav: "五稜郭公園",
        },
        {
          time: "15:24",
          type: "景點",
          title: "金森紅磚倉庫",
          desc: "參觀歷史建築群，購物與享用下午茶",
          about: "金森紅磚倉庫是函館港邊的歷史建築群，建於明治時代。現在已改建為購物中心、餐廳和咖啡廳，是函館的熱門觀光景點。",
          nav: "金森紅磚倉庫",
        },
        {
          time: "16:31",
          type: "美食",
          title: "迴轉壽司 根室花丸 Kiralis函館店",
          desc: "享用新鮮的迴轉壽司",
          about: "根室花丸是北海道知名的迴轉壽司連鎖店，以新鮮的海鮮和合理的價格著稱。Kiralis函館店位於函館市中心，交通便利。",
          nav: "迴轉壽司 根室花丸 Kiralis函館店",
        },
        {
          time: "17:47",
          type: "景點",
          title: "函館山觀景台",
          desc: "欣賞函館百萬夜景",
          about: "函館山夜景被譽為世界三大夜景之一，從觀景台可以俯瞰函館市區和港灣的璀璨燈光。建議在日落前抵達，欣賞從白天到夜晚的景色變化。",
          nav: "函館山觀景台",
        },
        {
          time: "18:58",
          type: "住宿",
          title: "OMO5 函館 by 星野集團",
          desc: "返回飯店休息",
          about: "回到飯店，可以在溫泉放鬆，或在 OMO Base 公共空間休息。",
          nav: "OMO5 函館 by 星野集團",
        },
      ],
    },
        {
      day: 6,
      date: "03/06 (週五)",
      title: "函館到小樽",
      location: "函館→小樽",
      weather: "",
      image:
        "https://images.unsplash.com/photo-1623310073404-fe9953eadb04?auto=format&fit=crop&w=1200&q=80",
      activities: [
        {
          time: "08:00",
          type: "住宿",
          title: "OMO5 函館 by 星野集團",
          desc: "退房，準備出發前往小樽",
          about: "從函館出發，開始今天的旅程。",
          nav: "OMO5 函館 by 星野集團",
        },
        {
          time: "08:39",
          type: "景點",
          title: "大沼國定公園",
          desc: "參觀大沼國定公園，欣賞湖泊與自然景觀",
          about: "大沼國定公園是北海道著名的自然公園，以大沼湖和小沼湖為中心，湖中有多個小島，可以划船或散步欣賞美景。春天時櫻花盛開，是熱門的賞櫻景點。",
          nav: "大沼國定公園",
        },
        {
          time: "11:36",
          type: "景點",
          title: "Lake Hill Farm",
          desc: "參觀 Lake Hill Farm，欣賞花園與農場風光",
          about: "Lake Hill Farm 是一個美麗的農場和花園，種植了各種花卉，四季都有不同的景色。可以購買農場產品和紀念品。",
          nav: "Lake Hill Farm",
        },
        {
          time: "12:53",
          type: "景點",
          title: "洞爺湖",
          desc: "參觀洞爺湖，欣賞湖光山色",
          about: "洞爺湖是北海道著名的火山口湖，湖水清澈，周圍環繞著美麗的山景。可以沿著湖邊散步，欣賞自然風光。",
          nav: "洞爺湖",
        },
        {
          time: "14:28",
          type: "景點",
          title: "地獄谷",
          desc: "參觀地獄谷，觀賞溫泉地熱景觀",
          about: "地獄谷是登別溫泉的著名景點，是一個火山口遺跡，不斷冒出硫磺蒸汽，形成獨特的地熱景觀。可以沿著步道參觀，感受大自然的威力。",
          nav: "地獄谷",
        },
        {
          time: "16:46",
          type: "景點",
          title: "小樽運河",
          desc: "參觀小樽運河，欣賞歷史建築與運河風光",
          about: "小樽運河是北海道最著名的觀光景點之一，兩旁保留著明治時代的倉庫建築，現在已改建為商店、餐廳和咖啡廳。夜晚時運河點燈，景色更加浪漫。",
          nav: "小樽運河",
        },
        {
          time: "18:50",
          type: "美食",
          title: "小樽倉庫No.1啤酒釀造所",
          desc: "參觀啤酒釀造所，品嚐當地釀造的啤酒",
          about: "小樽倉庫No.1啤酒釀造所是北海道知名的啤酒釀造廠，可以參觀釀造過程，並在餐廳品嚐新鮮釀造的啤酒和美食。",
          nav: "小樽倉庫No.1啤酒釀造所",
        },
        {
          time: "21:00",
          type: "住宿",
          title: "小樽格里茲頂級飯店",
          desc: "抵達飯店，辦理入住手續",
          about: "小樽格里茲頂級飯店位於小樽市中心，交通便利，提供舒適的住宿環境。",
          nav: "小樽格里茲頂級飯店",
        },
      ],
        },
        {
      day: 7,
      date: "03/07 (週六)",
      title: "小樽到富良野",
      location: "小樽→富良野",
      weather: "",
      image:
        "https://images.unsplash.com/photo-1623310073404-fe9953eadb04?auto=format&fit=crop&w=1200&q=80",
      activities: [
        {
          time: "08:00",
          type: "住宿",
          title: "小樽格里茲頂級飯店",
          desc: "退房，準備出發前往富良野",
          about: "從小樽出發，開始今天的旅程。",
          nav: "小樽格里茲頂級飯店",
        },
        {
          time: "10:29",
          type: "景點",
          title: "旭山動物園",
          desc: "參觀旭山動物園，觀賞各種動物",
          about: "旭山動物園是日本最北端的動物園，以獨特的展示方式聞名，讓遊客可以近距離觀察動物的自然行為。特別是企鵝散步和北極熊展示非常受歡迎。",
          nav: "旭山動物園",
        },
        {
          time: "13:28",
          type: "美食",
          title: "KINGBEAR 旭川緑町店",
          desc: "在 KINGBEAR 享用午餐",
          about: "KINGBEAR 是北海道知名的餐廳，提供美味的日式料理。旭川緑町店位於旭川市中心，交通便利。",
          nav: "KINGBEAR 旭川緑町店",
        },
        {
          time: "15:03",
          type: "景點",
          title: "Mild seven hills",
          desc: "參觀 Mild seven hills，欣賞自然景觀",
          about: "Mild seven hills 是富良野地區的著名景點，可以欣賞到美麗的山丘和自然風光。",
          nav: "Mild seven hills",
        },
        {
          time: "16:16",
          type: "景點",
          title: "Christmas tree",
          desc: "參觀 Christmas tree，欣賞雪景中的聖誕樹",
          about: "Christmas tree 是富良野地區的著名地標，一棵孤立的聖誕樹矗立在雪地中，形成獨特的景觀，是拍照的熱門地點。",
          nav: "Christmas tree",
        },
        {
          time: "18:12",
          type: "景點",
          title: "森林精靈露台",
          desc: "參觀森林精靈露台，欣賞夜晚的燈光與雪景",
          about: "森林精靈露台（Ningle Terrace）是富良野的著名景點，由多間小木屋組成的手工藝品商店區。夜晚時燈光點亮，在雪地中顯得格外浪漫。",
          nav: "森林精靈露台",
        },
        {
          time: "19:24",
          type: "美食",
          title: "Kumagera 一家提供餐飲和宴會的餐廳",
          desc: "在 Kumagera 享用晚餐",
          about: "Kumagera 是富良野地區知名的餐廳，提供日式料理和宴會服務，以新鮮的食材和傳統的烹飪方式著稱。",
          nav: "Kumagera",
        },
      ],
        },
        {
      day: 8,
      date: "03/08 (週日)",
      title: "富良野到札幌",
      location: "富良野→札幌",
      weather: "",
      image:
        "https://images.unsplash.com/photo-1623310073404-fe9953eadb04?auto=format&fit=crop&w=1200&q=80",
      activities: [
        {
          time: "10:00",
          type: "交通",
          title: "富良野站前",
          desc: "從富良野站出發",
          about: "富良野站是富良野地區的主要交通樞紐。",
          nav: "富良野站前",
        },
        {
          time: "10:04",
          type: "美食",
          title: "Boulangerie Lafi",
          desc: "在 Boulangerie Lafi 享用麵包或輕食",
          about: "Boulangerie Lafi 是富良野地區知名的麵包店，提供新鮮出爐的麵包和輕食。",
          nav: "Boulangerie Lafi",
        },
        {
          time: "10:40",
          type: "美食",
          title: "迴轉壽司 Topical",
          desc: "在迴轉壽司 Topical 享用壽司",
          about: "迴轉壽司 Topical 是富良野地區的迴轉壽司店，提供新鮮的海鮮壽司。",
          nav: "迴轉壽司 Topical",
        },
        {
          time: "11:51",
          type: "景點",
          title: "富良野滑雪場",
          desc: "參觀富良野滑雪場，欣賞雪景或體驗滑雪",
          about: "富良野滑雪場是北海道著名的滑雪勝地，冬季時可以滑雪，其他季節也可以欣賞美麗的山景。",
          nav: "富良野滑雪場",
        },
        {
          time: "14:54",
          type: "購物",
          title: "狸小路商店街",
          desc: "在狸小路商店街購物",
          about: "狸小路商店街是札幌最著名的購物街，全長約1公里，有許多商店、餐廳和藥妝店，是購物和體驗札幌市區氛圍的好地方。",
          nav: "狸小路商店街",
        },
        {
          time: "15:59",
          type: "住宿",
          title: "札幌格蘭貝爾酒店",
          desc: "抵達飯店，辦理入住手續",
          about: "札幌格蘭貝爾酒店位於札幌市中心，距離狸小路商店街很近，交通便利。",
          nav: "札幌格蘭貝爾酒店",
        },
        {
          time: "17:06",
          type: "景點",
          title: "大通公園",
          desc: "參觀大通公園，欣賞公園景觀",
          about: "大通公園是札幌市中心的大型公園，全長約1.5公里，是札幌的象徵性景點。冬季時會舉辦雪祭，平時也是市民休閒的好去處。",
          nav: "大通公園",
        },
        {
          time: "18:16",
          type: "景點",
          title: "札幌啤酒博物館",
          desc: "參觀札幌啤酒博物館，了解啤酒歷史",
          about: "札幌啤酒博物館展示札幌啤酒的歷史和釀造過程，可以了解日本啤酒文化的發展。",
          nav: "札幌啤酒博物館",
        },
        {
          time: "19:00",
          type: "美食",
          title: "サッポロビール園 開拓使館",
          desc: "在札幌啤酒園開拓使館享用晚餐",
          about: "札幌啤酒園開拓使館是札幌著名的餐廳，提供成吉思汗烤肉（烤羊肉）和啤酒，是體驗北海道美食文化的好地方。",
          nav: "サッポロビール園 開拓使館",
        },
      ],
        },
        {
      day: 9,
      date: "03/09 (週一)",
      title: "札幌市區",
      location: "札幌",
      weather: "",
      image:
        "https://images.unsplash.com/photo-1623310073404-fe9953eadb04?auto=format&fit=crop&w=1200&q=80",
      activities: [
        {
          time: "11:20",
          type: "美食",
          title: "Rojiura Curry SAMURAI(湯珈哩)",
          desc: "在 Rojiura Curry SAMURAI 享用湯咖哩",
          about: "Rojiura Curry SAMURAI 是札幌知名的湯咖哩餐廳，提供多種口味的湯咖哩，是札幌的特色美食之一。",
          nav: "Rojiura Curry SAMURAI",
        },
        {
          time: "12:43",
          type: "景點",
          title: "白色戀人公園",
          desc: "參觀白色戀人公園，體驗甜點製作與參觀工廠",
          about: "白色戀人公園是札幌著名的觀光景點，以白色戀人餅乾聞名。可以參觀餅乾製作過程、體驗甜點繪畫，並購買各種伴手禮。",
          nav: "白色戀人公園",
        },
      ],
        },
        {
      day: 10,
      date: "03/10 (週二)",
      title: "行程規劃中",
      location: "北海道",
      weather: "",
      image:
        "https://images.unsplash.com/photo-1623310073404-fe9953eadb04?auto=format&fit=crop&w=1200&q=80",
      activities: [],
    },
  ],
};
